// <auto-generated />
namespace SistemaTienda2._5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdiccionTablaFactura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdiccionTablaFactura));
        
        string IMigrationMetadata.Id
        {
            get { return "202404060541296_AdiccionTablaFactura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
